
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    expose:
      - 8000

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  